apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ghost-ai-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/digvijay-quapton/ghost-ai-service.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: ghost-ai
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false