apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vault-auth
  namespace: ghost-ai
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: apps
    serviceAccount: default
  vaultConnectionRef: default